# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid1, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='token',
        ),
        migrations.AlterField(
            model_name='event',
            name='downvote',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='upvote',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='session',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Device'),
        ),
    ]
