# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-30 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170930_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='upvote',
            field=models.IntegerField(default=1),
        ),
    ]
