# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trip_trip_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='photos'),
        ),
    ]
