# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_key',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
