# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event_event_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_type_id',
            new_name='device_registration_id',
        ),
    ]
